// Code generated by goyacc -l -o vdbparser.go vdbparser.y. DO NOT EDIT.
package vdbutil

import __yyfmt__ "fmt"

func setResult(l yyLexer, v Statement) {
	l.(*Tokenizer).Statement = v
}

type KeyValue struct {
	key string
	val string
}

type yySymType struct {
	yys       int
	statement Statement
	bytes     []byte
	mapstruct map[string]string
	str       string
	kv        KeyValue
}

const LEX_ERROR = 57346
const NUMBER = 57347
const LITERAL = 57348
const STRING = 57349
const CREATE = 57350
const DATABASE = 57351
const VERSION = 57352
const OPTIONS = 57353
const COMMENT = 57354
const SERVER = 57355
const FOREIGN = 57356
const DATA = 57357
const WRAPPER = 57358
const TRANSLATOR = 57359
const TYPE = 57360

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"NUMBER",
	"LITERAL",
	"STRING",
	"CREATE",
	"DATABASE",
	"VERSION",
	"OPTIONS",
	"COMMENT",
	"SERVER",
	"FOREIGN",
	"DATA",
	"WRAPPER",
	"TRANSLATOR",
	"TYPE",
	"';'",
	"'('",
	"')'",
	"','",
	"'\"'",
	"'\\''",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	-2, 4,
}

const yyPrivate = 57344

const yyLast = 61

var yyAct = [...]int{

	32, 47, 17, 30, 18, 36, 52, 53, 41, 35,
	10, 44, 31, 45, 21, 33, 22, 50, 23, 28,
	19, 20, 13, 39, 12, 29, 15, 14, 34, 25,
	3, 37, 8, 38, 40, 56, 57, 55, 48, 43,
	16, 42, 27, 49, 26, 9, 1, 46, 51, 11,
	24, 5, 59, 58, 54, 60, 7, 6, 4, 61,
	2,
}
var yyPact = [...]int{

	24, -1000, -9, -9, -1000, 12, -1000, -1000, 13, 24,
	-1000, -1000, -1000, -3, -1, -3, -1000, 19, -1000, 37,
	35, 3, -3, -6, 4, -3, -14, -19, -3, -6,
	9, -3, -1000, -12, -1000, -1000, -1000, -6, 4, -4,
	-1000, 31, 4, -1000, 1, -3, -15, -1000, 30, -1000,
	-3, 4, -1000, 31, -1000, -1000, -1000, -1000, 4, -1000,
	-1000, -1000,
}
var yyPgo = [...]int{

	0, 30, 60, 58, 57, 56, 54, 51, 2, 50,
	3, 0, 47, 1, 46, 45,
}
var yyR1 = [...]int{

	0, 14, 2, 2, 15, 15, 1, 1, 1, 1,
	3, 9, 9, 5, 5, 4, 4, 10, 10, 11,
	11, 12, 12, 12, 13, 8, 8, 8, 6, 6,
	6, 7, 7,
}
var yyR2 = [...]int{

	0, 1, 2, 3, 0, 1, 1, 1, 1, 1,
	5, 0, 2, 7, 6, 9, 8, 0, 2, 0,
	4, 0, 1, 3, 2, 1, 3, 3, 1, 1,
	1, 0, 2,
}
var yyChk = [...]int{

	-1000, -14, -2, -1, -3, -7, -4, -5, 8, -15,
	19, -15, 12, 9, 14, 13, -1, -8, 7, 23,
	24, 15, 17, -8, -9, 10, 7, 7, 16, -8,
	-10, 18, -11, 11, -8, 23, 24, -8, -10, 14,
	-8, 20, -10, -11, 15, 17, -12, -13, 7, -11,
	16, -8, 21, 22, -6, 7, 5, 6, -8, -11,
	-13, -11,
}
var yyDef = [...]int{

	31, -2, -2, 4, 6, 7, 8, 9, 0, 31,
	5, 2, 32, 0, 0, 0, 3, 11, 25, 0,
	0, 0, 0, 17, 19, 0, 0, 0, 0, 17,
	0, 0, 10, 0, 12, 26, 27, 17, 19, 0,
	18, 21, 19, 14, 0, 0, 0, 22, 0, 13,
	0, 19, 20, 0, 24, 28, 29, 30, 19, 16,
	23, 15,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 23, 3, 3, 3, 3, 24,
	20, 21, 3, 3, 22, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 19,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			setResult(yylex, yyDollar[1].statement)
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			setResult(yylex, yyDollar[3].statement)
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			addComment(string(yyDollar[1].bytes))
		}
	case 10:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			setDatabase(string(yyDollar[3].bytes), string(yyDollar[4].bytes), yyDollar[5].mapstruct)
		}
	case 11:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bytes = []byte("1")
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 13:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			addDataWrapper(string(yyDollar[5].bytes), string(yyDollar[6].bytes), yyDollar[7].mapstruct)
		}
	case 14:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			addDataWrapper(string(yyDollar[4].bytes), string(yyDollar[5].bytes), yyDollar[6].mapstruct)
		}
	case 15:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			addServer(string(yyDollar[3].bytes), string(yyDollar[8].bytes), yyDollar[9].mapstruct)
		}
	case 16:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			addServer(string(yyDollar[3].bytes), string(yyDollar[7].bytes), yyDollar[8].mapstruct)
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bytes = []byte("")
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.mapstruct = map[string]string{}
		}
	case 20:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.mapstruct = yyDollar[3].mapstruct
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.mapstruct = map[string]string{}
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.mapstruct = map[string]string{
				yyDollar[1].kv.key: yyDollar[1].kv.val,
			}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].mapstruct[yyDollar[3].kv.key] = yyDollar[3].kv.val
			yyVAL.mapstruct = yyDollar[1].mapstruct
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.kv = KeyValue{key: string(yyDollar[1].bytes), val: string(yyDollar[2].bytes)}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bytes = nil
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.bytes = []byte(string(yyDollar[1].bytes) + string(yyDollar[2].bytes))
		}
	}
	goto yystack /* stack new state and value */
}
